name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: List repo files
        run: ls -R

      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu   # or ec2-user if Amazon Linux
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /home/ubuntu/cicdgroceryfullstack

      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          debug: true
          script: |
            cd ~/cicdgroceryfullstack
            sudo apt-get update -y
            sudo apt-get install -y git docker docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo docker-compose down || true
            sudo docker-compose up -d --build
